# Codes used on league website, to something I prefer to read
CODE_TO_NAME = {
  "BUF" => "Buffalo",
  "CLE" => "Cleveland",
  "NO"  => "New Orleans",
  "NE"  => "New England",
  "DET" => "Detroit",
  "GB"  => "Green Bay",
  "SEA" => "Seattle",
  "BAL" => "Baltimore",
  "MIA" => "Miami",
  "MIN" => "Minnesota",
  "CIN" => "Cincinnati",
  "PHI" => "Philadelphia",
  "PIT" => "Pittsburgh",
  "CHI" => "Chicago",
  "IND" => "Indianapolis",
  "NYG" => "NY Giants",
  "JAC" => "Jacksonville",
  "STL" => "St. Louis",
  "KC"  => "Kansas City",
  "TEN" => "Tennessee",
  "CAR" => "Carolina",
  "ARI" => "Arizona",
  "DEN" => "Denver",
  "DAL" => "Dallas",
  "HOU" => "Houston",
  "SF"  => "San Francisco",
  "SD"  => "San Diego",
  "OAK" => "Oakland",
  "NYJ" => "NY Jets",
  "WAS" => "Washington",
  "TB"  => "Tampa Bay",
  "ATL" => "Atlanta"
}

TEAM_GEOS = CODE_TO_NAME.values
